### ISSUE TITLE
인풋폼 글자제한 필요

### ISSUE THREAD

**Issue by LaziesFirst** [LaziesFirst/learningcurve-test#10]
![KakaoTalk_Photo_2023-09-09-23-21-21](https://github.com/LaziesFirst/learningcurve-test/assets/62410444/9aef5899-f843-43f8-abbe-18d381627729)

디비랑 달라서 에러남 20자 제한

**Comment by LaziesFirst** [comment]
서버에서 20자 제한처리했음

**Comment by LaziesFirst** [comment]
- [x] 레이블명
- [x] 전화번호
- [ ] 이메일
- [ ] 그 외 인풋 텍스트 필드

**Comment by dbaudwns20** [comment]
운영서버 반영완료
