### ISSUE TITLE
알림 유형 필드에 텍스트 입력이 됨

### ISSUE THREAD

**Issue by Aiden-Jeon** [LaziesFirst/learningcurve-test#11]
![image](https://github.com/LaziesFirst/learningcurve-test/assets/33924485/3a826506-468c-47f4-9d53-f59ec5a18e14)

**Comment by LaziesFirst** [comment]
이 케이스는 입력 막고 선택만 가능하게 처리

**Comment by dbaudwns20** [comment]
모든 select 컴포넌트 readonly 처리
