### ISSUE TITLE
학생 성적 그래프 중 응시 이후부터 점수가 나오면 어떨 지?

### ISSUE THREAD

**Issue by Aiden-Jeon** [LaziesFirst/learningcurve-test#14]
![image](https://github.com/LaziesFirst/learningcurve-test/assets/33924485/e413ce92-c55f-45cb-acd3-1f9ab460c1c8)

앞에서 진행한 시험이 많은 경우 평균이 낮게 나올 듯 ?

**Comment by LaziesFirst** [comment]
그래프 겹치는 경우 내 점수 -> 전체평균 -> 최고점수 순으로 맨 앞에서 표현되게 처리하기
내 평균은 미참여 제외하고 계산하기

**Comment by dbaudwns20** [comment]
운영서버 반영완료
