### ISSUE TITLE
이미지 사이즈 넘어가는 것처럼 보임

### ISSUE THREAD

**Issue by LaziesFirst** [LaziesFirst/learningcurve-test#16]
![스크린샷 2023-09-10 오전 12 06 34](https://github.com/LaziesFirst/learningcurve-test/assets/62410444/f59f3da9-d165-4cc8-a742-af72e4e1c4b5)

**Comment by LaziesFirst** [comment]
![스크린샷 2023-09-10 오전 12 11 11](https://github.com/LaziesFirst/learningcurve-test/assets/62410444/d4a24c01-498d-4b85-a126-6de3928739d7)

**Comment by dbaudwns20** [comment]
운영서버 배포 완료
