### ISSUE TITLE
시간에 올바르지 않은 형식을 입력할 수 있음

### ISSUE THREAD

**Issue by Aiden-Jeon** [LaziesFirst/learningcurve-test#6]
![image](https://github.com/LaziesFirst/learningcurve-test/assets/33924485/b42a052b-c4c6-4959-9155-4fbe7c604bfc)
프리셋으로 제공하거나 text 값을 허용하게 해주거나 해야할 듯

**Comment by dbaudwns20** [comment]
#11 동일 이슈, readonly 처리. 단순 선택만 가능하도록 변경
