### ISSUE TITLE
시험 점수가 학생 본인에게만 공개여도 전체 공개 됨

### ISSUE THREAD

**Issue by Aiden-Jeon** [LaziesFirst/learningcurve-test#7]
![image](https://github.com/LaziesFirst/learningcurve-test/assets/33924485/3c96bc03-b43d-48f5-90c6-de40926ed231)

남에게 나옴

**Comment by Aiden-Jeon** [comment]
시험 성적이 입력된 적이 없는 경우

**Comment by Aiden-Jeon** [comment]
성적이 입력되는 경우 정상 동작 확인
![image](https://github.com/LaziesFirst/learningcurve-test/assets/33924485/e898c7b6-4287-4f3d-aea9-85a090f92419)

**Comment by LaziesFirst** [comment]
성적이 입력되지 않은 경우 이름 마스킹 안되는 버그 수정
